// const std = @import("std");
// const Lexer = @import("compiler/lexer.zig").Lexer;
// const Parser = @import("compiler/parser.zig").Parser;
// const Node = @import("compiler/ast.zig").Node;

// fn printPadding(padding: usize) void {
//     var i: usize = 0;
//     while (i < padding) : (i += 1) {
//         std.debug.print("  ", .{});
//     }
// }

// fn printAST(node: *Node, padding: usize) void {
//     printPadding(padding);

//     switch (node.*) {
//         .number => |n| std.debug.print("Number: {d}\n", .{n}),
//         .variable => |v| std.debug.print("Variable: {s}\n", .{v}),
//         .assignment => |a| {
//             std.debug.print("Assignment: let {s} =\n", .{a.name});
//             printAST(a.value, padding + 1);
//         },
//         .binary_op => |b| {
//             std.debug.print("BinaryOp: {s}\n", .{@tagName(b.op)});
//             printAST(b.l, padding + 1);
//             printAST(b.r, padding + 1);
//         },
//     }
// }

// pub fn main() !void {
//     // const source = "let x = 10 + 5 + 3 + 5 + 6 +3 +9;";
//     // std.debug.print("SOURCE CODE:\n{s}\n\n", .{source});

//     // var lexer = Lexer{ .source = source };

//     // var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
//     // defer arena.deinit();
//     // const allocator = arena.allocator();

//     // var parser = Parser.init(&lexer, allocator);

//     // const ast_tree = parser.parseStatement() catch |err| {
//     //     std.debug.print("Failed to parse: {any}\n", .{err});
//     //     return;
//     // };

//     // std.debug.print("ABSTRACT SYNTAX TREE:\n", .{});
//     // printAST(ast_tree, 0);

// }

const std = @import("std");
const Lexer = @import("compiler/lexer.zig").Lexer;
const Parser = @import("compiler/parser.zig").Parser;
const Compiler = @import("compiler/generator.zig").Compiler;
const VM = @import("vm/vm.zig").VM;
const OpCode = @import("vm/instructions.zig").OpCode;

pub fn main() !void {
    const source = "let x = 10 + 5 + 3 + 10;";
    std.debug.print("=== 1. SOURCE CODE ===\n{s}\n\n", .{source});

    // Инициализация памяти (Arena для AST, обычный аллокатор для байт-кода)
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var lexer = Lexer{ .source = source };
    var parser = Parser.init(&lexer, allocator);

    const ast_tree = parser.parseStatement() catch |err| {
        std.debug.print("Parse error: {any}\n", .{err});
        return;
    };
    std.debug.print("=== 2. AST SUCCESS ===\n\n", .{});

    var compiler = Compiler.init(allocator);
    defer compiler.deinit();

    // Генерируем код из дерева
    compiler.genNode(ast_tree) catch |err| {
        std.debug.print("Compile error: {any}\n", .{err});
        return;
    };

    try compiler.bytecode.append(allocator, @intFromEnum(OpCode.halt));

    const program = compiler.bytecode.items;

    std.debug.print("=== 3. GENERATED BYTECODE ===\n", .{});
    for (program) |byte| {
        std.debug.print("{d} ", .{byte});
    }
    std.debug.print("\n\n", .{});

    std.debug.print("=== 4. VM EXECUTION ===\n", .{});
    var vm = VM{}; // Инициализируем нашу машину
    vm.run(program);


    std.debug.print("\n=== 5. FINAL STATE ===\n", .{});

    std.debug.print("Memory[0] (variable 'x') = {d}\n", .{vm.mem.data[0]});
}
